function [handles] = updateOrientation(handles,r,rotMat)
    set(handles.xAxis,'XData',r(1)+[0 rotMat(1,1)],...
                      'YData',r(2)+[0 rotMat(1,2)],...
                      'ZData',r(3)+[0 rotMat(1,3)]);
    set(handles.yAxis,'XData',r(1)+[0 rotMat(2,1)],...
                      'YData',r(2)+[0 rotMat(2,2)],...
                      'ZData',r(3)+[0 rotMat(2,3)]);
    set(handles.zAxis,'XData',r(1)+[0 rotMat(3,1)],...
                      'YData',r(2)+[0 rotMat(3,2)],...
                      'ZData',r(3)+[0 rotMat(3,3)]);
end